export const authLayoutStyles = {
  container: "min-h-screen flex bg-zinc-950",
  leftPanel: "flex-1 hidden lg:flex flex-col justify-between bg-gradient-to-br from-zinc-900 via-zinc-950 to-zinc-900 p-12 relative overflow-hidden",
  glowTop: "absolute -top-40 -right-40 w-80 h-80 bg-emerald-500/10 rounded-full blur-3xl",
  glowBottom: "absolute -bottom-40 -left-40 w-80 h-80 bg-emerald-500/5 rounded-full blur-3xl",
  logoContainer: "relative z-10",
  logoText: "text-2xl font-bold font-['Satoshi'] text-emerald-400",
  mainCopyContainer: "relative z-10 space-y-8",
  liveBadge: "inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-[10px] font-semibold uppercase tracking-widest text-emerald-300",
  dot: "w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse",
  mainCopyInner: "space-y-4",
  heading: "text-5xl font-bold text-white leading-[1.1] font-['Satoshi']",
  emeraldText: "text-emerald-400",
  description: "text-zinc-400 text-lg leading-relaxed max-w-md",
  statsGrid: "flex gap-4",
  statCard: "bg-white/5 rounded-xl px-5 py-4 backdrop-blur-sm border border-white/5 hover:bg-white/[0.07] transition-all",
  statValue: "text-xl font-bold text-white",
  statLabel: "text-xs text-zinc-500 mt-0.5",
  footer: "relative z-10 text-xs text-zinc-700",
  rightPanel: "flex-1 flex items-center justify-center p-6",
  mobileLogoContainer: "lg:hidden mb-8",
  mobileLogoText: "text-2xl font-bold font-['Satoshi'] text-emerald-400",
};

export const loginStyles = {
  error: "flex items-center gap-2 rounded-xl bg-rose-500/10 border border-rose-500/20 px-4 py-3 mb-6",
  errorIcon: "shrink-0 text-rose-400",
  errorText: "text-rose-300 text-xs",
  form: "space-y-5",
  field: "space-y-1.5",
  label: "text-xs font-semibold text-zinc-400 uppercase tracking-wide",
  inputWrapper: "relative",
  input: "w-full rounded-xl border border-zinc-700/80 bg-zinc-800/50 px-4 py-3 text-white placeholder:text-zinc-600 outline-none transition-all focus:border-emerald-500/60 text-sm",
  inputWithIcon: "pl-10",
  icon: "absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-500 pointer-events-none",
  passwordRow: "flex items-center justify-between",
  forgotLink: "text-[11px] font-medium text-zinc-500 hover:text-emerald-400 transition-colors",
  toggleButton: "absolute right-3.5 top-1/2 -translate-y-1/2 text-zinc-500 hover:text-zinc-300 transition-colors",
  submitButton: "w-full rounded-xl bg-emerald-500 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-400 active:scale-[0.98] transition-all disabled:opacity-50 shadow-lg shadow-emerald-500/25",
};

export const signupStyles = {
  errorBox: "flex items-center gap-2 rounded-xl bg-rose-500/10 border border-rose-500/20 px-4 py-3 mb-6",
  errorIcon: "shrink-0 text-rose-400",
  errorText: "text-rose-300 text-xs",
  form: "space-y-4",
  field: "space-y-1.5",
  label: "text-xs font-semibold text-zinc-400 uppercase tracking-wide",
  toggleButton: "absolute right-3.5 top-1/2 -translate-y-1/2 text-zinc-500 hover:text-zinc-300 transition-colors",
  strengthContainer: "flex gap-1 mt-1.5",
  strengthBarBase: "h-1 flex-1 rounded-full transition-all duration-300",
  strengthInactive: "bg-zinc-800",
  strengthWeak: "bg-rose-500",
  strengthMedium: "bg-amber-500",
  strengthStrong: "bg-emerald-400",
  strengthVeryStrong: "bg-emerald-500",
};

export const forgotPasswordStyles = {
  errorBox: "flex items-center gap-2 rounded-xl bg-rose-500/10 border border-rose-500/20 px-4 py-3 mb-6",
  errorIcon: "shrink-0 text-rose-400",
  errorText: "text-rose-300 text-xs",
  emailForm: "space-y-5",
  emailInputWrapper: "space-y-1.5",
  label: "text-xs font-semibold text-zinc-400 uppercase tracking-wide",
};

export const createPollStyles = {
  heading: "text-lg font-bold text-white mb-6 font-['Satoshi']",
  errorBox: "flex items-center gap-2 rounded-xl bg-rose-500/10 border border-rose-500/20 px-4 py-3 mb-4 text-rose-300 text-xs",
  form: "space-y-5",
  label: "text-xs font-semibold text-zinc-400 uppercase tracking-wide mb-1.5 block",
  textarea: "min-h-24 resize-y",
  typeButtonBase: "inline-flex items-center gap-1.5 px-3.5 py-2 rounded-lg text-xs font-semibold transition-all border",
  typeButtonActive: "bg-emerald-500/10 border-emerald-500/30 text-emerald-400",
  typeButtonInactive: "bg-zinc-800/50 border-zinc-700/50 text-zinc-500 hover:border-zinc-600 hover:text-zinc-300",
  optionsContainer: "space-y-2",
  optionInputWrapper: "flex items-center gap-2",
  optionDeleteButton: "p-1.5 rounded-lg hover:bg-zinc-800 transition-colors shrink-0",
  addOptionButton: "w-full flex items-center justify-center gap-1.5 py-2.5 text-xs font-semibold",
  submitButton: "w-full text-center py-2.5 text-sm",
};

export const analyticsStyles = {
  container: "max-w-2xl mx-auto py-8 px-4",
  heading: "text-lg font-bold text-white mb-6 font-['Satoshi']",
  statsGrid: "grid grid-cols-2 gap-4",
  statCard: "bg-zinc-900/70 border border-zinc-800/80 rounded-2xl p-5",
  statValue: "text-2xl font-bold text-white",
  statLabel: "text-xs text-zinc-500 mt-1",
};

export const settingsStyles = {
  container: "max-w-2xl mx-auto py-8 px-4 space-y-8",
  heading: "text-lg font-bold text-white mb-6 font-['Satoshi']",
  section: "bg-zinc-900/70 border border-zinc-800/80 rounded-2xl p-5",
  sectionTitle: "text-sm font-semibold text-zinc-100 mb-4",
  label: "text-xs font-semibold text-zinc-400 uppercase tracking-wide mb-1.5 block",
  passwordForm: "space-y-3",
  avatarWrap: "flex items-center gap-4 mb-5",
  avatarImg: "w-16 h-16 rounded-full object-cover bg-zinc-800",
  avatarOverlay: "absolute inset-0 rounded-full bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer",
  avatarUploadBtn: "text-[10px] font-semibold text-white",
  usernameRow: "flex items-center gap-2",
  usernameInput: "flex-1",
  usernameCheck: "text-[10px] font-semibold px-2.5 py-1 rounded-lg",
  usernameAvailable: "text-emerald-400 bg-emerald-500/10",
  usernameTaken: "text-rose-400 bg-rose-500/10",
  usernameLoading: "text-zinc-500 bg-zinc-800",
  inputHint: "text-[10px] text-zinc-600 mt-1",
};

export const userProfileStyles = {
  errorContainer: "text-zinc-500 text-sm py-8 text-center",
  profileCard: "bg-zinc-900/70 border border-zinc-800/80 rounded-2xl overflow-hidden mb-6",
  bannerContainer: "h-20 bg-gradient-to-r from-emerald-500/10 via-emerald-500/5 to-transparent relative",
  bannerGlow: "absolute inset-0 bg-gradient-to-b from-emerald-500/5 to-transparent",
  profileBody: "px-5 pb-5 -mt-10",
  avatarRow: "mb-3",
  avatarClass: "w-20 h-20 rounded-xl border-2 border-zinc-900 shadow-lg",
  userInfo: "mb-4",
  userName: "text-lg font-bold text-white",
  userUsername: "text-sm text-zinc-500",
  userBio: "text-sm text-zinc-400 mt-2 leading-relaxed",
  statsRow: "flex gap-4 flex-wrap",
  statNumber: "text-base font-bold text-white",
  statLabel: "text-xs text-zinc-500",
  pollsHeading: "text-sm font-semibold text-zinc-400 uppercase tracking-wide mb-4",
  emptyPolls: "text-sm text-zinc-600 text-center py-6",
};

export const singlePollPageStyles = {
  errorContainer: "text-zinc-500 text-sm py-8 text-center",
  backButton: "inline-flex items-center gap-1.5 text-xs text-zinc-500 hover:text-zinc-300 transition-colors mb-4",
};

export const layoutStyles = {
  container: "min-h-screen bg-zinc-950",
  header: "sticky top-0 z-40 bg-zinc-950/90 backdrop-blur-xl border-b border-zinc-800/60 transition-shadow duration-200",
  headerInner: "max-w-7xl mx-auto px-4 h-14 flex items-center gap-3",
  logoLink: "flex items-center gap-2 shrink-0 group",
  logoSpan: "hidden sm:block text-[15px] font-bold text-white tracking-tight",
  searchDesktop: "hidden md:flex flex-1 max-w-md mx-auto relative",
  searchIcon: "absolute left-3 top-1/2 -translate-y-1/2 text-zinc-600 pointer-events-none",
  searchInput: "w-full rounded-xl bg-zinc-900 border border-zinc-800 pl-8 pr-4 py-2 text-sm text-zinc-300 placeholder:text-zinc-600 outline-none transition-all duration-150 hover:border-zinc-700 focus:border-emerald-500/50 focus:ring-1 focus:ring-emerald-500/20",
  rightCluster: "flex items-center gap-1.5 ml-auto md:ml-0 shrink-0",
  createButton: "hidden sm:inline-flex items-center gap-1.5 rounded-xl bg-emerald-500 text-white px-3.5 py-2 text-sm font-semibold hover:bg-emerald-400 active:scale-95 transition-all duration-150 shadow-lg shadow-emerald-500/25",
  avatarClass: "w-7 h-7 text-xs ring-1 ring-zinc-700",
  bodyContainer: "max-w-7xl mx-auto px-0 sm:px-4 flex gap-5 xl:gap-6",
  leftSidebar: "hidden lg:flex flex-col w-52 shrink-0 sticky top-14 self-start h-[calc(100vh-3.5rem)] py-6 pr-1",
  menuLabel: "px-3 mb-2 text-[10px] font-bold text-zinc-700 uppercase tracking-widest",
  navContainer: "space-y-0.5 flex-1",
  sideLinkBase: "flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all duration-150",
  sideLinkActive: "bg-emerald-500/10 text-emerald-400 font-semibold border border-emerald-500/20",
  sideLinkInactive: "text-zinc-500 hover:text-zinc-200 hover:bg-zinc-800/60",
  sidebarBottom: "pt-4 border-t border-zinc-800/60 space-y-0.5",
  logoutButton: "w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium text-rose-500 hover:bg-rose-500/8 transition-colors duration-150",
  mainContent: "flex-1 min-w-0 max-w-2xl mx-auto py-5 pb-24 lg:pb-6 max-lg:px-3",
  rightRail: "hidden xl:flex flex-col w-72 shrink-0 pt-5 pb-5 gap-3 sticky top-14 self-start",
  bottomNav: "lg:hidden fixed bottom-0 inset-x-0 z-40 bg-zinc-950/95 backdrop-blur-xl border-t border-zinc-800/60 flex justify-around px-2 pt-1.5 pb-2 max-lg:rounded-t-2xl max-lg:shadow-[0_-4px_20px_rgba(0,0,0,0.4)]",
  bottomLinkBase: "flex flex-col items-center gap-0.5 py-1.5 px-3 text-[10px] font-semibold transition-colors duration-150",
  bottomLinkActive: "text-emerald-400",
  bottomLinkInactive: "text-zinc-600",
  bottomLinkDot: "w-1 h-1 rounded-full bg-emerald-400 mt-0.5",
};

export const cardStyles = {
  card: "bg-zinc-900/70 border border-zinc-800/80 rounded-2xl overflow-hidden",
  header: "flex items-center gap-2.5 mb-2",
  avatar: "w-7 h-7 rounded-full shrink-0",
  userInfo: "flex-1 min-w-0",
  userInfoInner: "flex items-center gap-1 text-xs truncate",
  userNameLink: "font-semibold text-zinc-300 hover:text-emerald-400 transition-colors truncate",
  dot: "text-zinc-700 shrink-0",
  username: "text-zinc-600 truncate",
  timestamp: "text-zinc-600 whitespace-nowrap shrink-0",
  closedBadge: "inline-flex items-center gap-1 text-[10px] font-bold text-amber-400 bg-amber-500/10 border border-amber-500/20 px-2 py-0.5 rounded-full shrink-0",
  categoryTagBase: "text-[10px] font-semibold px-2 py-0.5 rounded-full border shrink-0",
  ownerControls: "flex items-center gap-1 mb-2",
  ownerButton: "p-1.5 rounded-lg text-zinc-600 hover:text-zinc-300 hover:bg-zinc-800/60",
  ownerAnalytics: "p-1.5 rounded-lg text-zinc-600 hover:text-emerald-400 hover:bg-zinc-800/60",
  ownerDelete: "p-1.5 rounded-lg text-zinc-600 hover:text-rose-400 hover:bg-zinc-800/60 ml-auto",
  sharePopover: "absolute top-full left-0 mt-1 z-50 bg-zinc-800 border border-zinc-700 rounded-xl p-1 shadow-xl min-w-32",
  shareOption: "flex items-center gap-2 px-3 py-2 text-xs text-zinc-300 hover:bg-zinc-700 rounded-lg w-full",
  editTextarea: "min-h-16 resize-y text-sm",
  editButton: "text-xs font-semibold px-3 py-1.5 rounded-lg bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20",
  question: "text-sm font-semibold text-zinc-100 mb-3 leading-relaxed",
  footer: "flex items-center gap-4 mt-3 pt-3 border-t border-zinc-800/50",
  totalVotes: "flex items-center gap-1 text-xs text-zinc-600 font-medium",
  action: "flex items-center gap-1 text-xs text-zinc-600 hover:text-zinc-300",
  actionActive: "text-emerald-400",
  saveIconFill: "fill-emerald-400",
};

export const pollCardStyles = {
  card: "bg-zinc-900/70 border border-zinc-800/80 rounded-2xl overflow-hidden",
  header: "flex items-center gap-2.5 mb-2",
  avatar: "w-7 h-7 rounded-full shrink-0",
  userInfo: "flex-1 min-w-0",
  userInfoInner: "flex items-center gap-1 text-xs truncate",
  userNameLink: "font-semibold text-zinc-300 hover:text-emerald-400 transition-colors truncate",
  dot: "text-zinc-700 shrink-0",
  username: "text-zinc-600 truncate",
  timestamp: "text-zinc-600 whitespace-nowrap shrink-0",
  closedBadge: "inline-flex items-center gap-1 text-[10px] font-bold text-amber-400 bg-amber-500/10 border border-amber-500/20 px-2 py-0.5 rounded-full shrink-0",
  categoryTagBase: "text-[10px] font-semibold px-2 py-0.5 rounded-full border shrink-0",
  ownerControls: "flex items-center gap-1 mb-2",
  ownerButton: "p-1.5 rounded-lg text-zinc-600 hover:text-zinc-300 hover:bg-zinc-800/60 transition-all",
  ownerAnalytics: "p-1.5 rounded-lg text-zinc-600 hover:text-emerald-400 hover:bg-zinc-800/60 transition-all",
  ownerDelete: "p-1.5 rounded-lg text-zinc-600 hover:text-rose-400 hover:bg-zinc-800/60 transition-all ml-auto",
  sharePopover: "absolute top-full left-0 mt-1 z-50 bg-zinc-800 border border-zinc-700 rounded-xl p-1 shadow-2xl shadow-black/40 min-w-32 origin-top-left transition-all duration-100",
  shareOption: "flex items-center gap-2 px-3 py-2 text-xs text-zinc-300 hover:bg-zinc-700 rounded-lg w-full transition-colors",
  editTextarea: "min-h-16 resize-y text-sm",
  editButton: "text-xs font-semibold px-3 py-1.5 rounded-lg bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 transition-colors",
  question: "text-sm font-semibold text-zinc-100 mb-3 leading-relaxed",
  footer: "flex items-center gap-4 mt-3 pt-3 border-t border-zinc-800/50",
  totalVotes: "flex items-center gap-1 text-xs text-zinc-600 font-medium",
  action: "flex items-center gap-1 text-xs text-zinc-600 hover:text-zinc-300 transition-colors",
  actionActive: "text-emerald-400",
  saveIconFill: "fill-emerald-400",
};

export const pollVoteStyles = {
  yesNoGrid: "grid grid-cols-2 gap-2 mb-3",
  yesNoButtonBase: "flex items-center justify-center gap-1.5 py-2.5 rounded-xl text-xs font-semibold transition-all duration-150 active:scale-[0.97] border",
  yesNoButtonYesInactive: "bg-zinc-800/70 border-zinc-700/70 text-zinc-300 hover:bg-emerald-500/10 hover:border-emerald-500/30 hover:text-emerald-400",
  yesNoButtonYesActive: "bg-emerald-500/10 border-emerald-500/30 text-emerald-400",
  yesNoButtonNoInactive: "bg-zinc-800/70 border-zinc-700/70 text-zinc-300 hover:bg-rose-500/10 hover:border-rose-500/30 hover:text-rose-400",
  yesNoButtonNoActive: "bg-rose-500/10 border-rose-500/30 text-rose-400",
  singleContainer: "space-y-1.5 mb-3",
  singleOptionBase: "w-full flex items-center gap-2.5 px-3.5 py-2.5 rounded-xl text-xs font-medium transition-all duration-150 active:scale-[0.98] border text-left",
  singleOptionInactive: "bg-zinc-800/50 border-zinc-700/50 text-zinc-300 hover:bg-zinc-800/80 hover:border-zinc-600",
  singleOptionActive: "bg-emerald-500/8 border-emerald-500/25 text-emerald-300",
  singleOptionCircleBase: "w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold shrink-0 transition-all",
  singleOptionCircleInactive: "bg-zinc-700/80 text-zinc-500",
  singleOptionCircleActive: "bg-emerald-500/20 text-emerald-400",
  singleUndoHint: "text-[10px] text-zinc-600 ml-auto",
  ratingContainer: "flex flex-col items-center gap-2 mb-3 py-2 relative",
  ratingStars: "flex gap-1",
  ratingStarButton: "p-1 transition-transform hover:scale-110",
  ratingStarFilled: "text-amber-400 fill-amber-400",
  ratingStarEmpty: "text-zinc-700",
  ratingSubmit: "text-xs font-semibold px-4 py-1.5 rounded-lg bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 transition-all",
  ratingHint: "text-[10px] text-zinc-600",
  ratingUndoHint: "text-[10px] text-zinc-600",
  imageGrid: "grid grid-cols-3 gap-2 mb-3",
  imageItemBase: "relative rounded-xl overflow-hidden border-2 aspect-square group/img",
  imageItemActive: "border-emerald-400 ring-2 ring-emerald-400/30",
  imageItemSelected: "border-emerald-500/50",
  imageItemInactive: "border-zinc-700/50 hover:border-zinc-600",
  imageThumb: "w-full h-full object-cover",
  imageCheck: "absolute top-1.5 right-1.5 w-5 h-5 rounded-full bg-emerald-500 flex items-center justify-center text-white shadow-lg",
  imageUndoText: "absolute bottom-1 left-1/2 -translate-x-1/2 text-[9px] font-medium text-rose-300 bg-zinc-900/80 px-1.5 py-0.5 rounded whitespace-nowrap",
  imageSubmit: "w-full text-xs font-semibold py-2 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 hover:bg-emerald-500/20 transition-all",
  openTextarea: "min-h-20 resize-y text-sm mb-2",
  openFooter: "flex items-center justify-between mb-3",
  openCharCount: "text-[10px] text-zinc-600",
  openSubmit: "text-xs font-semibold px-3 py-1.5 rounded-lg bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 transition-all disabled:opacity-40",
};

export const pollResultsStyles = {
  resultBarBase: "relative h-9 rounded-lg overflow-hidden cursor-pointer border",
  resultBarDefault: "border-zinc-700/50",
  resultBarHighlight: "border-emerald-500/30 bg-emerald-500/5",
  resultBarFill: "absolute inset-0 bg-zinc-800",
  resultBarFillDefault: "bg-zinc-800",
  resultBarFillHighlight: "bg-emerald-500/15",
  resultBarFillWinner: "bg-zinc-800/80",
  resultBarContent: "absolute inset-0 flex items-center justify-between px-3",
  resultBarLabelBase: "flex items-center gap-1 text-xs font-medium transition-colors",
  resultBarLabelDefault: "text-zinc-400",
  resultBarLabelHighlight: "text-emerald-300",
  resultBarCheck: "text-emerald-400",
  resultBarUndoIcon: "text-rose-400/70 animate-pulse",
  resultBarPercentBase: "text-xs font-bold transition-colors",
  resultBarPercentDefault: "text-zinc-500",
  resultBarPercentHighlight: "text-emerald-300",
  resultBarUndoHint: "text-[9px] text-rose-400/70 mr-1.5",
  versusEmpty: "text-xs text-zinc-600 text-center py-4",
  versusBarContainer: "flex h-8 rounded-full overflow-hidden bg-zinc-800 mb-2",
  versusYesBase: "flex items-center justify-center text-xs font-bold text-emerald-200 transition-all bg-emerald-500/30 hover:bg-emerald-500/40 cursor-pointer",
  versusYesHover: "hover:bg-emerald-500/40",
  versusNoBase: "flex items-center justify-center text-xs font-bold text-rose-200 transition-all bg-rose-500/30 hover:bg-rose-500/40 cursor-pointer",
  versusNoHover: "hover:bg-rose-500/40",
  versusLabels: "flex items-center justify-between text-xs",
  versusLabelYesBase: "flex items-center gap-1 font-medium cursor-pointer transition-colors",
  versusLabelYesInactive: "text-zinc-500 hover:text-emerald-400",
  versusLabelYesActive: "text-emerald-400",
  versusLabelNoBase: "flex items-center gap-1 font-medium cursor-pointer transition-colors",
  versusLabelNoInactive: "text-zinc-500 hover:text-rose-400",
  versusLabelNoActive: "text-rose-400",
  versusVoteCount: "text-[10px] text-zinc-600",
  versusUndoHint: "text-[9px] text-zinc-600 ml-1",
  openContainer: "space-y-1.5 mb-3 max-h-44 overflow-y-auto",
  openHeader: "text-[10px] font-semibold text-zinc-500 uppercase tracking-wider mb-2",
  openResponse: "text-xs text-zinc-400 bg-zinc-800/50 rounded-lg px-3 py-2 leading-relaxed",
  openEmpty: "text-xs text-zinc-600 text-center py-3",
  imageGrid: "grid grid-cols-3 gap-2 mb-3",
  imageItemBase: "relative rounded-xl overflow-hidden border-2 transition-all aspect-square group/img",
  imageItemActive: "border-emerald-400 ring-2 ring-emerald-400/30",
  imageItemInactive: "border-zinc-700/50 hover:border-zinc-600",
  imageThumb: "w-full h-full object-cover",
  imageBadge: "absolute top-1.5 right-1.5 w-5 h-5 rounded-full bg-emerald-500 flex items-center justify-center text-white shadow-lg",
  imageUndoText: "absolute bottom-1 left-1/2 -translate-x-1/2 text-[9px] font-medium text-rose-300 bg-zinc-900/80 px-1.5 py-0.5 rounded whitespace-nowrap",
  ratingSummary: "flex items-center gap-2 py-2",
  ratingAverage: "text-lg font-bold text-amber-400",
  ratingStars: "flex gap-0.5",
  starFilled: "text-amber-400 fill-amber-400",
  starEmpty: "text-zinc-700",
  ratingCount: "text-[10px] text-zinc-600",
  totalVotesText: "text-[10px] text-zinc-600 text-center pt-1",
};

export const commentsStyles = {
  commentsContainer: "mt-4 space-y-4 border-t border-zinc-800/50 pt-4",
  mainForm: "flex gap-2",
  mainInput: "flex-1 rounded-xl border border-zinc-700/80 bg-zinc-800/50 px-3.5 py-2 text-xs text-white placeholder:text-zinc-600 outline-none focus:border-emerald-500/60 transition-all",
  mainSubmit: "px-3 py-2 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 hover:bg-emerald-500/20 transition-all disabled:opacity-40",
  commentList: "space-y-4",
  emptyText: "text-xs text-zinc-600 text-center py-4",
  commentItem: "flex gap-2.5",
  avatarSmall: "w-6 h-6 rounded-full shrink-0 mt-0.5",
  commentContent: "flex-1 min-w-0",
  commentBubble: "bg-zinc-800/50 rounded-xl px-3 py-2",
  commentHeader: "flex items-center gap-2 mb-0.5",
  usernameLink: "text-[11px] font-semibold text-zinc-400 hover:text-emerald-400 transition-colors",
  timestamp: "text-[10px] text-zinc-700",
  commentText: "text-xs text-zinc-300 leading-relaxed",
  commentActions: "flex items-center gap-3 mt-1 px-1",
  replyButton: "text-[10px] font-medium text-zinc-700 hover:text-emerald-400 transition-colors",
  deleteButton: "text-[10px] font-medium text-zinc-700 hover:text-rose-400 transition-colors inline-flex items-center gap-0.5",
  replyForm: "flex gap-1.5 mt-1.5",
  replyInput: "flex-1 rounded-xl bg-zinc-800 border border-zinc-700/60 px-2.5 py-1.5 text-[11px] text-zinc-300 placeholder:text-zinc-600 outline-none focus:border-emerald-500/50 transition-all",
  replySubmit: "w-7 h-7 grid place-items-center rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 hover:bg-emerald-500/20 transition-colors shrink-0",
  repliesContainer: "ml-6 mt-2 space-y-2 border-l border-zinc-800/60 pl-3",
  replyItem: "flex gap-2",
  replyIndent: "shrink-0 mt-2 text-zinc-700",
  avatarTiny: "w-5 h-5 rounded-full shrink-0 mt-0.5",
  replyBubble: "flex-1 min-w-0 bg-zinc-800/30 rounded-xl px-2.5 py-1.5",
  replyHeader: "flex items-center gap-2 mb-0.5",
  replyUsername: "text-[10px] font-semibold text-zinc-500 hover:text-emerald-400 transition-colors",
  replyTimestamp: "text-[9px] text-zinc-700",
  replyText: "text-[11px] text-zinc-400 leading-relaxed",
  replyDelete: "text-[10px] font-medium text-zinc-700 hover:text-rose-400 transition-colors inline-flex items-center gap-0.5 mt-0.5",
};

export const connectionsStyles = {
  container: "bg-zinc-900/70 border border-zinc-800/80 rounded-2xl p-4",
  tabContainer: "flex gap-2 mb-4",
  tabButtonBase: "flex-1 text-xs font-semibold py-2 rounded-lg transition-all",
  tabButtonActive: "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20",
  tabButtonInactive: "text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800/50 border border-transparent",
  emptyText: "text-xs text-zinc-600 text-center py-6",
  userList: "space-y-2",
  userLink: "flex items-center gap-2.5 p-2 rounded-lg hover:bg-zinc-800/50 transition-colors",
  userAvatar: "w-8 h-8 rounded-full shrink-0",
  userInfo: "flex-1 min-w-0",
  userName: "text-xs font-semibold text-zinc-300 truncate",
  userUsername: "text-[10px] text-zinc-600 truncate",
};

export const sidebarStyles = {
  profileCard: "relative bg-zinc-900/80 border border-zinc-800/80 rounded-2xl p-5 overflow-hidden",
  glowBlob: "absolute -top-8 left-1/2 -translate-x-1/2 w-44 h-24 bg-emerald-500/15 blur-3xl rounded-full pointer-events-none",
  profileInner: "relative flex flex-col items-center text-center",
  avatarWrapper: "relative",
  avatarGlow: "absolute -inset-1.5 rounded-full bg-emerald-500/25 blur-md",
  avatarClass: "relative w-16 h-16 text-lg ring-2 ring-zinc-800",
  userNameLink: "mt-3 text-sm font-semibold text-zinc-200 hover:text-white transition-colors",
  usernameText: "text-xs text-zinc-600 mt-0.5",
  statsContainer: "relative mt-5 pt-4 border-t border-zinc-800/80 grid grid-cols-3 divide-x divide-zinc-800/80",
  statBox: "text-center",
  statNumber: "text-base font-bold text-white tabular-nums",
  statLabel: "text-[10px] text-zinc-600 mt-0.5 uppercase tracking-wide",
  viewProfileLink: "relative mt-4 flex items-center justify-center rounded-xl bg-emerald-500 text-white hover:bg-emerald-400 text-xs font-semibold py-1.5 w-full transition-all duration-150 active:scale-[0.97] shadow-lg shadow-emerald-500/25",
  trendingCard: "bg-zinc-900/80 border border-zinc-800/80 rounded-2xl p-4",
  trendingHeading: "text-[10px] font-bold text-zinc-700 uppercase tracking-widest mb-4 flex items-center gap-2",
  trendingIcon: "text-emerald-500",
  trendingList: "space-y-3",
  trendingItemRow: "flex justify-between items-center mb-1.5",
  trendingItemLabel: "text-xs text-zinc-500 flex items-center gap-1.5",
  trendingItemIcon: "text-zinc-700",
  trendingItemCount: "text-xs font-semibold text-zinc-600 tabular-nums",
  trendingBarTrack: "h-0.5 rounded-full bg-zinc-800",
  trendingBarFillBase: "h-0.5 rounded-full",
};

export const notificationStyles = {
  bellButton: "relative p-1.5 rounded-lg text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800 transition-colors",
  unreadDot: "absolute -top-1.5 -right-1.5 min-w-[18px] h-[18px] flex items-center justify-center rounded-full bg-rose-500 ring-2 ring-zinc-900 text-[10px] font-bold text-white px-1",
  dropdown: "absolute right-0 top-full mt-2 w-80 bg-zinc-900 border border-zinc-800 rounded-xl shadow-2xl overflow-hidden z-50 max-h-96 overflow-y-auto",
  dropdownHeader: "flex items-center justify-between text-[10px] font-semibold text-zinc-500 uppercase tracking-wider px-3 py-2 border-b border-zinc-800 sticky top-0 bg-zinc-900",
  markAllRead: "text-[10px] font-semibold text-emerald-400 hover:text-emerald-300 normal-case tracking-normal",
  notifItem: "flex items-start gap-2.5 px-3 py-2.5 hover:bg-zinc-800/50 transition-colors border-b border-zinc-800/50 last:border-0 cursor-pointer",
  notifUnread: "bg-emerald-500/5",
  notifIconContainer: "w-6 h-6 rounded-full bg-zinc-800 flex items-center justify-center shrink-0 mt-0.5",
  notifIconUnread: "bg-emerald-500/15 text-emerald-400",
  notifContent: "flex-1 min-w-0",
  notifText: "text-xs text-zinc-400 leading-relaxed",
  notifPollText: "text-zinc-600 italic",
  notifTime: "text-[10px] text-zinc-700 mt-0.5 flex items-center gap-1.5",
  unreadIndicator: "w-1.5 h-1.5 rounded-full bg-emerald-400 inline-block",
  emptyText: "text-xs text-zinc-600 text-center py-6",
};

export const toastStyles = {
  container: "fixed top-4 right-4 z-50 flex flex-col gap-2",
  toastBase: "flex items-center gap-2 px-4 py-3 rounded-xl shadow-2xl border text-sm transition-all",
  toastSuccess: "bg-zinc-900 border-emerald-500/30 text-emerald-400",
  toastError: "bg-zinc-900 border-rose-500/30 text-rose-400",
};

export const uiElementStyles = {
  btnBase: "inline-flex items-center justify-center gap-1.5 rounded-lg text-xs font-semibold transition-all duration-150 active:scale-[0.97] disabled:opacity-50 disabled:pointer-events-none",
  btnPrimary: "bg-emerald-500 text-white hover:bg-emerald-400 shadow-lg shadow-emerald-500/25 px-3.5 py-2",
  btnGhost: "text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 px-3 py-1.5",
  btnDanger: "text-rose-400 hover:text-rose-300 hover:bg-rose-500/10 px-3 py-1.5",
  inputCls: "w-full rounded-xl border border-zinc-700/80 bg-zinc-800/50 px-4 py-2.5 text-white placeholder:text-zinc-600 outline-none transition-all duration-150 focus:border-emerald-500/60 focus:ring-1 focus:ring-emerald-500/20 text-sm",
  authButton: "w-full inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-bold bg-emerald-500 text-white hover:bg-emerald-400 active:scale-[0.98] disabled:opacity-50 disabled:pointer-events-none transition-all duration-150 shadow-lg shadow-emerald-500/25",
  fieldLabel: "text-xs font-semibold text-zinc-400 uppercase tracking-wide block mb-1.5",
  avatarImg: "object-cover rounded-full",
  avatarPlaceholder: "flex items-center justify-center rounded-full bg-gradient-to-br from-emerald-500 to-emerald-600 text-white text-sm font-bold",
  skeletonContainer: "space-y-3",
  skeletonCard: "bg-zinc-900/70 border border-zinc-800/80 rounded-2xl p-4",
  skeletonAvatar: "w-7 h-7 rounded-full bg-zinc-800",
  skeletonName: "h-3 bg-zinc-800 rounded w-20",
  skeletonUsername: "h-3 bg-zinc-800 rounded w-16",
  skeletonCategory: "h-3 bg-zinc-800 rounded w-14 ml-auto",
  skeletonQuestion: "h-4 bg-zinc-800 rounded w-3/4 mb-4",
  skeletonOptions: "space-y-2 mb-3",
  skeletonOption1: "h-8 bg-zinc-800 rounded-xl w-full",
  skeletonOption2: "h-8 bg-zinc-800 rounded-xl w-2/3",
  skeletonFooter: "flex gap-4 pt-3 border-t border-zinc-800/50",
  skeletonAction1: "h-3 bg-zinc-800 rounded w-12",
  skeletonAction2: "h-3 bg-zinc-800 rounded w-12",
  skeletonAction3: "h-3 bg-zinc-800 rounded w-12 ml-auto",
};

export const otpStepStyles = {
  form: "space-y-5",
  emailBadge: "flex items-center gap-2.5 rounded-xl bg-zinc-800/50 border border-zinc-700/50 px-3.5 py-3",
  emailIconWrapper: "w-8 h-8 rounded-lg bg-emerald-500/10 flex items-center justify-center shrink-0 text-emerald-400",
  emailLabel: "text-[10px] text-zinc-600",
  emailValue: "text-xs font-semibold text-zinc-300 truncate",
  errorBox: "text-xs text-rose-300 bg-rose-500/10 border border-rose-500/20 rounded-lg px-3 py-2",
  otpLabel: "text-xs font-semibold text-zinc-400 uppercase tracking-wide block mb-1",
  otpInput: "w-full text-center text-lg tracking-[0.5em] font-bold bg-zinc-800/50 border border-zinc-700/80 rounded-xl px-4 py-3 text-white outline-none focus:border-emerald-500/60 transition-all",
  otpDotsContainer: "flex justify-center gap-1.5 mt-2",
  otpDot: "w-2 h-2 rounded-full transition-all duration-300",
  otpDotFilled: "bg-emerald-400 scale-110",
  otpDotEmpty: "bg-zinc-700",
  resendText: "text-xs text-zinc-600",
  resendTimer: "font-semibold text-zinc-400",
  resendButton: "inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-400 hover:text-emerald-300 transition-colors",
  resendIcon: "animate-spin",
  spinner: "w-4 h-4 animate-spin",
  spinnerCircle: "opacity-25",
  spinnerPath: "opacity-75",
};

export const dashboardStyles = {
  container: "space-y-6",
  pageHeader: "flex items-center justify-between",
  greetingContainer: "",
  greetingText: "text-xl font-bold text-white font-['Satoshi']",
  greetingSubtext: "text-sm text-zinc-500 mt-0.5",
  createButton: "hidden sm:inline-flex items-center gap-2 rounded-xl bg-emerald-500 text-white px-4 py-2.5 text-sm font-semibold hover:bg-emerald-400 transition-all shadow-lg shadow-emerald-500/25",
  composer: "flex gap-3 bg-zinc-900/70 border border-zinc-800/80 rounded-2xl p-4 items-start",
  composerAvatar: "w-9 h-9 rounded-full shrink-0",
  composerBody: "flex-1 flex flex-col gap-3",
  composerInput: "w-full bg-transparent text-sm text-zinc-100 placeholder-zinc-600 outline-none resize-none",
  composerFooter: "flex items-center justify-between",
  composerTypes: "flex items-center gap-1",
  composerTypeBtn: "p-1.5 rounded-lg",
  composerTypeActive: "bg-emerald-500/15 text-emerald-400",
  composerTypeInactive: "text-zinc-600 hover:text-zinc-400 hover:bg-zinc-800/50",
  composerSubmit: "text-xs font-semibold px-4 py-1.5 rounded-lg bg-emerald-500 text-white hover:bg-emerald-400 transition-all disabled:opacity-40 disabled:cursor-not-allowed",
  pollsHeader: "flex items-center justify-between",
  pollsTitle: "text-sm font-semibold text-zinc-400 uppercase tracking-wider",
  pollsCount: "text-xs text-zinc-600",
  emptyState: "text-center py-16",
  emptyIcon: "mx-auto text-zinc-700 mb-4",
  emptyText: "text-zinc-500 text-sm",
  emptyCreateButton: "inline-block mt-3 rounded-xl bg-emerald-500 text-white px-5 py-2.5 text-sm font-semibold hover:bg-emerald-400 transition-all shadow-lg shadow-emerald-500/25",
};

export const appStyles = {
  container: "min-h-screen bg-zinc-950 text-zinc-300",
};

export const filterBarStyles = {
  container: "flex gap-1.5 overflow-x-auto pb-1 scrollbar-none",
  filterBase: "flex items-center gap-1 px-3 py-1.5 rounded-lg text-[11px] font-semibold transition-all whitespace-nowrap border",
  filterActive: "bg-emerald-500/10 border-emerald-500/25 text-emerald-400",
  filterInactive: "bg-zinc-800/50 border-zinc-700/50 text-zinc-500 hover:border-zinc-600 hover:text-zinc-300",
};
